# railway.toml

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "uvicorn main:app --reload"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"