# railway.toml

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/invalid-path"
healthcheckTimeout = 120
restartPolicyType = "never"